{
	"version": 1499092594,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/plataformanorte-sheet0.png",
		"images/personagem-sheet0.png",
		"images/personagem-sheet1.png",
		"images/blocopersonagem-sheet0.png",
		"images/menu-sheet0.png",
		"images/musicasnorte-sheet0.png",
		"images/musicanordeste-sheet0.png",
		"images/musicacentrooeste-sheet0.png",
		"images/musicasul-sheet0.png",
		"images/objetonorte2-sheet0.png",
		"images/botãogame-sheet0.png",
		"images/botãocredt-sheet0.png",
		"images/musicasudeste-sheet0.png",
		"images/limiteagua-sheet0.png",
		"images/objetonorte3-sheet0.png",
		"images/objetosul1-sheet0.png",
		"images/objetosul2-sheet0.png",
		"images/objetonordeste1-sheet0.png",
		"images/objetonordeste2-sheet0.png",
		"images/objetonordeste3-sheet0.png",
		"images/animalnorte-sheet0.png",
		"images/sensoranimais-sheet0.png",
		"images/fundoagua-sheet0.png",
		"images/mapafundo-sheet0.png",
		"images/telafim-sheet0.png",
		"images/objetonorte1-sheet0.png",
		"images/animalnordeste-sheet0.png",
		"images/animalco-sheet0.png",
		"images/objetosudeste1-sheet0.png",
		"images/objetosudeste2-sheet0.png",
		"images/animalsul-sheet0.png",
		"images/animalsudeste-sheet0.png",
		"images/botãohistoria-sheet0.png",
		"images/objetosudeste3-sheet0.png",
		"images/telavitoria-sheet0.png",
		"images/telascreditohistoria-sheet0.png",
		"images/objetoco1-sheet0.png",
		"images/plataformanortenordeste-sheet0.png",
		"images/objetoco2-sheet0.png",
		"media/marujada(região norte).ogg",
		"media/caboclinhos(região nordeste).ogg",
		"media/quadrilha(região centro-oeste).ogg",
		"media/musica_tema.m4a",
		"media/musica_tema.ogg",
		"media/musica_intro (online-audio-converter.com) (1).ogg",
		"media/catira(região centro-oeste).ogg",
		"media/funk(regiãosudeste).ogg",
		"media/instrumentalchamarritaregiãosul (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}